### PR TITLE
Added groovy init script for plugin global configuration.

### PR DESCRIPTION
**Pull request by Constantin07**
This PR explains how to automate the global configuration of SumoLogic plugin using groovy script.

The script was tested on a latest `2.184` version of Jenkins.

### CODE REVIEW

**Comment by Constantin07** [comment]
@SumoSourabh please can this PR be reviewed ?
PS: not sure who exactly needs to be included though.

**Comment by SumoSourabh** [comment]
Thanks for the groovy script.

I will look into it and let you know the details.

**Comment by SumoSourabh** [comment]
Let me check if we can put the groovy file as well as so a person can directly use the groovy file instead of creating one.

**Comment by SumoSourabh** [comment]
@Constantin07 Are you able to send logs to SumoLogic?

**Comment by Constantin07** [comment]
@SumoSourabh I do see some logs. Some of them come as under `logmessage` json field (build success/failure), some of them appear under built in `Message` field (git checkouts).

**Comment by SumoSourabh** [comment]
Thanks @Constantin07 . The new app for jenkins is also Live.

**Comment by SumoSourabh** [comment]
Changes have been included as file and updated the README.md accordingly. 

https://github.com/SumoLogic/sumologic-jenkins-plugin/pull/26

Closing the PR as changes will go via the above PR.

**Pull request closed without merging**
